# Weekly pull requests for dependency updates, including security fixes.
version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule: {interval: weekly}
  - package-ecosystem: npm
    directory: /web
    schedule: {interval: weekly}
    groups:
      web-dev-tools:
        dependency-type: development
  - package-ecosystem: pub
    directory: /mobile
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directories: [/backend, /web]
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
